In [4]:
import pandas as pd
import os

file_path = 'pacientes_uci'
df_patients = pd.read_csv(os.path.join(file_path,'datapatients.txt'), delimiter="\t")
df_mdilcode = pd.read_csv(os.path.join(file_path,'mdilcode.txt'), delimiter="\t")
df_ingreso = pd.read_csv(os.path.join(file_path,'Pacientes_ingreso_egreso_UCI_Monitores.txt'), delimiter="\t")

In [5]:
df_patients

,country,state,city,headquarter,msgid,ubication,bed,datetimeevent,datetimesystem,observationid,observationvalue,observationidunits,datainsert
0,Colombia,Antioquia,Medellín,Las Américas,HP171077070010786,PMA-UCI-P2,CAMA4,20240318090500,18/3/2024 10:42:11,0002-f081,0.00,0004-0aa0,18/3/2024 10:42:11.-1f
1,Colombia,Antioquia,Medellín,Las Américas,HP171077070010787,PMA-UCI-P2,CAMA5,20240318090500,18/3/2024 10:42:11,0002-d006,"""""",NaN,18/3/2024 10:42:11.-1f
2,Colombia,Antioquia,Medellín,Las Américas,HP171077070010787,PMA-UCI-P2,CAMA5,20240318090500,18/3/2024 10:42:11,0002-d007,Taqui Sinusal,NaN,18/3/2024 10:42:11.-1f
3,Colombia,Antioquia,Medellín,Las Américas,HP171077070010787,PMA-UCI-P2,CAMA5,20240318090500,18/3/2024 10:42:11,0002-4bb8,94,0004-0220,18/3/2024 10:42:11.-1f
4,Colombia,Antioquia,Medellín,Las Américas,HP171077070010787,PMA-UCI-P2,CAMA5,20240318090500,18/3/2024 10:42:11,0002-5000,36,0004-0ae0,18/3/2024 10:42:11.-1f
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4585802,Colombia,Antioquia,Medellín,Las Américas,HP171077070010786,PMA-UCI-P2,CAMA4,20240318090500,18/3/2024 10:42:11,0002-4a11,147,0004-0f20,18/3/2024 10:42:11.-1f
4585803,Colombia,Antioquia,Medellín,Las Américas,HP171077070010786,PMA-UCI-P2,CAMA4,20240318090500,18/3/2024 10:42:11,0002-4a12,82,0004-0f20,18/3/2024 10:42:11.-1f
4585804,Colombia,Antioquia,Medellín,Las Américas,HP171077070010786,PMA-UCI-P2,CAMA4,20240318090500,18/3/2024 10:42:11,0002-4a13,104,0004-0f20,18/3/2024 10:42:11.-1f
4585805,Colombia,Antioquia,Medellín,Las Américas,HP171077070010786,PMA-UCI-P2,CAMA4,20240318090500,18/3/2024 10:42:11,0002-4182,107,0004-0aa0,18/3/2024 10:42:11.-1f
4585806,Colombia,Antioquia,Medellín,Las Américas,HP171077070010786,PMA-UCI-P2,CAMA4,20240318090500,18/3/2024 10:42:11,0002-4261,107,0004-0aa0,18/3/2024 10:42:11.-1f

In [6]:
df_mdilcode

,mdilcode,parameterlabel,description,typeparameter
0,0002-0302,ST-II,ST lead II,typeObservation
1,0002-4182,HR,Heart Rate,typeObservation
2,0002-4261,PVC,Premature Ventricular Counted Beats,typeObservation
3,0002-4822,Pulse,Pulse Rate from Plethysmogram,typeObservation
4,0002-4a05,NBPs,Non-invasive blood pressure (systolic),typeObservation
...,...,...,...,...
192,0002-4a33,LAPm,LAP (mean),typeObservation
193,0002-5012,AwRR,Airway Respiration Rate,typeObservation
194,0002-50b0,etCO2,End-Tidal CO2 Concentration,typeObservation
195,0002-50ba,imCO2,Inspired Minimum CO2,typeObservation
196,0002-580b,ICPm,ICP (mean),typeObservation

In [7]:
df_ingreso

,historia,ingreso,centro_costos,cama,fecha_ingreso_servicio,hora_ingreso_servicio,fecha_egreso_servicio,hora_egreso_servicio
0,f816e5cd59e6d1bcae5c2017bcffd2427088b5b02df5f0...,1,1020,CAMA4,24/2/2024,00:36:02,27/2/2024,13:45:47
1,a81823ef6f343ade3f6f5a05f9ffc8c43c88e0a8f6d2cf...,3,1020,CAMA7,26/2/2024,14:03:46,1/3/2024,10:56:03
2,2ef64c67cf84cb832c0fc635b0a0c840e582841979c933...,11,1020,CAMA3,26/2/2024,19:53:53,27/2/2024,21:53:34
3,5a87e3f903fc8e2eaae72865e3050d54578321421355a0...,1,1020,CAMA2,27/2/2024,03:13:50,27/2/2024,11:13:23
4,57f77e0311561333efd51573770b761b1021d933430237...,11,1020,CAMA11,27/2/2024,12:10:07,2/3/2024,14:04:26
...,...,...,...,...,...,...,...,...
95,1747dda34ca1a419480d01e45e94c30082b2723d8e821b...,1,1020,CAMA10,8/4/2024,14:43:37,9/4/2024,17:10:42
96,b2430f988f48f86c85da996dedcc2751eb3cd6971c0004...,28,1020,CAMA1,8/4/2024,19:05:43,10/4/2024,16:06:17
97,a1e685dd832a8ff63fbb3aaec67cb09d02048780515221...,9,1020,CAMA5,9/4/2024,13:51:10,NaN,NaN
98,7ef30283c92e545ba168e924d13409d6a3b9895befc9e9...,4,1020,CAMA7,9/4/2024,19:10:49,NaN,NaN
99,ce5af639b8897e9027239476b8c02359a9f0b3a9c8a6bd...,13,1020,CAMA10,10/4/2024,18:27:24,NaN,NaN

In [8]:
output_csv_path = os.path.join(file_path, 'datapatients.csv')
df_patients.to_csv(output_csv_path, index=False)

In [9]:
output_csv_path = os.path.join(file_path, 'df_mdilcode.csv')
df_mdilcode.to_csv(output_csv_path, index=False)

In [10]:
output_csv_path = os.path.join(file_path, 'df_ingreso.csv')
df_ingreso.to_csv(output_csv_path, index=False)

In [12]:
import pandas as pd
import re


file_path = './Coronaria/cleve.mod'


with open(file_path, 'r') as file:
    lines = file.readlines()
    data_lines = [line for line in lines if not line.startswith('%')]


data_str = ''.join(data_lines)


pattern = r'(\d+\.\d+|\d+|male|fem|angina|abnang|notang|asympt|true|fal|norm|hyp|fix|rev|buff|sick|H|S\d)'

data = [re.findall(pattern, line) for line in data_lines if re.search(pattern, line)]


columns = ['Age', 'Sex', 'ChestPainType', 'Trestbps', 'Cholesterol', 'FastingBloodSugar',
           'RestingECG', 'MaxHeartRate', 'ExerciseInducedAngina', 'Oldpeak', 'Slope',
           'NumberOfVessels', 'Thal', 'Class']

df_cleve_mod = pd.DataFrame(data, columns=columns)


print(df_cleve_mod)

      Age   Sex ChestPainType Trestbps Cholesterol FastingBloodSugar  \
0    63.0  male        angina    145.0       233.0              true
1    67.0  male        asympt    160.0       286.0               fal
2    67.0  male        asympt    120.0       229.0               fal
3    37.0  male        notang    130.0       250.0               fal
4    41.0   fem        abnang    130.0       204.0               fal
..    ...   ...           ...      ...         ...               ...
298  48.0  male        notang    124.0       255.0              true
299  57.0  male        asympt    132.0       207.0               fal
300  49.0  male        notang    118.0       149.0               fal
301  74.0   fem        abnang    120.0       269.0               fal
302  54.0   fem        notang    160.0       201.0               fal

    RestingECG MaxHeartRate ExerciseInducedAngina Oldpeak Slope  \
0          hyp        150.0                   fal     2.3   0.0
1          hyp        108.0                  true     1.5   3.0
2          hyp        129.0                  true     2.6   2.0
3         norm        187.0                   fal     3.5   0.0
4          hyp        172.0                   fal     1.4   0.0
..         ...          ...                   ...     ...   ...
298       norm        175.0                   fal     0.0   2.0
299       norm        168.0                  true     0.0   0.0
300        hyp        126.0                   fal     0.8   3.0
301        hyp        121.0                  true     0.2   1.0
302       norm        163.0                   fal     0.0   1.0

    NumberOfVessels  Thal Class
0               fix  buff     H
1              norm  sick    S2
2               rev  sick    S1
3              norm  buff     H
4              norm  buff     H
..              ...   ...   ...
298            norm  buff     H
299             rev  buff     H
300            norm  sick    S1
301            norm  buff     H
302            norm  buff     H

[303 rows x 14 columns]

In [13]:
df_cleve_mod

,Age,Sex,ChestPainType,Trestbps,Cholesterol,FastingBloodSugar,RestingECG,MaxHeartRate,ExerciseInducedAngina,Oldpeak,Slope,NumberOfVessels,Thal,Class
0,63.0,male,angina,145.0,233.0,true,hyp,150.0,fal,2.3,0.0,fix,buff,H
1,67.0,male,asympt,160.0,286.0,fal,hyp,108.0,true,1.5,3.0,norm,sick,S2
2,67.0,male,asympt,120.0,229.0,fal,hyp,129.0,true,2.6,2.0,rev,sick,S1
3,37.0,male,notang,130.0,250.0,fal,norm,187.0,fal,3.5,0.0,norm,buff,H
4,41.0,fem,abnang,130.0,204.0,fal,hyp,172.0,fal,1.4,0.0,norm,buff,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,48.0,male,notang,124.0,255.0,true,norm,175.0,fal,0.0,2.0,norm,buff,H
299,57.0,male,asympt,132.0,207.0,fal,norm,168.0,true,0.0,0.0,rev,buff,H
300,49.0,male,notang,118.0,149.0,fal,hyp,126.0,fal,0.8,3.0,norm,sick,S1
301,74.0,fem,abnang,120.0,269.0,fal,hyp,121.0,true,0.2,1.0,norm,buff,H
302,54.0,fem,notang,160.0,201.0,fal,norm,163.0,fal,0.0,1.0,norm,buff,H

In [14]:
output_csv_path = './Coronaria/cleve_mod.csv'
df_cleve_mod.to_csv(output_csv_path, index=False)
print(f"DataFrame exportado a {output_csv_path}")

DataFrame exportado a ./Coronaria/cleve_mod.csv